using MathCity.Domain.Entities;
using MathCity.Domain.Enums;
using MathCity.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;

namespace MathCity.Infrastructure.Seed.Lessons;

public static class SequencesAndSeriesLessonSeeder
{
    public static async Task SeedAsync(ApplicationDbContext context)
    {
        var topics = await context.Topics
            .ToDictionaryAsync(t => t.Title);

        var lessons = new List<Lesson>
        {
            // ==========================================================
// Arithmetic Progression (AP)
// ==========================================================

new Lesson
{
    TopicId = topics["Arithmetic Progression (AP)"].Id,
    Title = "Introduction to Arithmetic Progression",
    Slug = "introduction-to-arithmetic-progression",
    Summary = "Learn the fundamentals of arithmetic progression, understand common differences, and discover how terms are generated in a sequence.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Arithmetic Progression (AP)"].Id,
    Title = "Finding Terms and Sum of Arithmetic Progression",
    Slug = "finding-terms-and-sum-of-arithmetic-progression",
    Summary = "Explore formulas for the nth term and the sum of an arithmetic progression, and solve problems involving arithmetic sequences step-by-step.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Arithmetic Progression (AP)"].Id,
    Title = "Applications and Practice of Arithmetic Progression",
    Slug = "applications-and-practice-of-arithmetic-progression",
    Summary = "Apply arithmetic progression concepts to solve advanced mathematical problems and explore their applications in finance, scheduling, engineering, and real-world pattern analysis.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Geometric Progression (GP)
// ==========================================================

new Lesson
{
    TopicId = topics["Geometric Progression (GP)"].Id,
    Title = "Introduction to Geometric Progression",
    Slug = "introduction-to-geometric-progression",
    Summary = "Learn the fundamentals of geometric progression, understand common ratios, and discover how each term is generated by multiplying the previous term.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Geometric Progression (GP)"].Id,
    Title = "Finding Terms and Sum of Geometric Progression",
    Slug = "finding-terms-and-sum-of-geometric-progression",
    Summary = "Explore formulas for the nth term, finite sum, and infinite sum of a geometric progression, and solve problems step-by-step.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Geometric Progression (GP)"].Id,
    Title = "Applications and Practice of Geometric Progression",
    Slug = "applications-and-practice-of-geometric-progression",
    Summary = "Apply geometric progression concepts to solve advanced mathematical problems and explore applications in finance, population growth, computer science, and compound interest.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Harmonic Progression (HP)
// ==========================================================

new Lesson
{
    TopicId = topics["Harmonic Progression (HP)"].Id,
    Title = "Introduction to Harmonic Progression",
    Slug = "introduction-to-harmonic-progression",
    Summary = "Learn the fundamentals of harmonic progression, understand how it is formed from the reciprocals of an arithmetic progression, and explore its basic properties.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Harmonic Progression (HP)"].Id,
    Title = "Solving Problems Using Harmonic Progression",
    Slug = "solving-problems-using-harmonic-progression",
    Summary = "Explore methods for identifying harmonic progressions, finding terms, and solving mathematical problems involving reciprocal relationships.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Harmonic Progression (HP)"].Id,
    Title = "Applications and Practice of Harmonic Progression",
    Slug = "applications-and-practice-of-harmonic-progression",
    Summary = "Apply harmonic progression concepts to solve advanced mathematical problems and explore applications in physics, engineering, acoustics, optics, and rate-based calculations.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Sigma Notation
// ==========================================================

new Lesson
{
    TopicId = topics["Sigma Notation"].Id,
    Title = "Introduction to Sigma Notation",
    Slug = "introduction-to-sigma-notation",
    Summary = "Learn the fundamentals of sigma notation and understand how it provides a compact way to represent the sum of a sequence of numbers.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Sigma Notation"].Id,
    Title = "Evaluating Expressions Using Sigma Notation",
    Slug = "evaluating-expressions-using-sigma-notation",
    Summary = "Explore how to evaluate sigma expressions, simplify summations, and apply summation formulas to solve mathematical problems efficiently.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Sigma Notation"].Id,
    Title = "Applications and Practice of Sigma Notation",
    Slug = "applications-and-practice-of-sigma-notation",
    Summary = "Apply sigma notation to solve advanced mathematical problems and explore its applications in statistics, calculus, computer science, finance, and scientific computations.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Finite Series
// ==========================================================

new Lesson
{
    TopicId = topics["Finite Series"].Id,
    Title = "Introduction to Finite Series",
    Slug = "introduction-to-finite-series",
    Summary = "Learn the fundamentals of finite series, understand how a fixed number of terms are added together, and explore common types of finite sums.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Finite Series"].Id,
    Title = "Evaluating and Solving Finite Series",
    Slug = "evaluating-and-solving-finite-series",
    Summary = "Explore formulas and techniques for evaluating finite arithmetic, geometric, and other series, and solve summation problems step-by-step.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Finite Series"].Id,
    Title = "Applications and Practice of Finite Series",
    Slug = "applications-and-practice-of-finite-series",
    Summary = "Apply finite series concepts to solve advanced mathematical problems and explore applications in finance, engineering, statistics, computer science, and scientific calculations.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Infinite Series
// ==========================================================

new Lesson
{
    TopicId = topics["Infinite Series"].Id,
    Title = "Introduction to Infinite Series",
    Slug = "introduction-to-infinite-series",
    Summary = "Learn the fundamentals of infinite series, understand how infinitely many terms are added together, and explore the concepts of convergence and divergence.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Infinite Series"].Id,
    Title = "Convergence and Evaluation of Infinite Series",
    Slug = "convergence-and-evaluation-of-infinite-series",
    Summary = "Explore methods for determining whether an infinite series converges or diverges, evaluate common infinite series, and understand important convergence tests.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Infinite Series"].Id,
    Title = "Applications and Practice of Infinite Series",
    Slug = "applications-and-practice-of-infinite-series",
    Summary = "Apply infinite series concepts to solve advanced mathematical problems and explore applications in calculus, physics, engineering, computer science, and numerical analysis.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Binomial Expansion
// ==========================================================

new Lesson
{
    TopicId = topics["Binomial Expansion"].Id,
    Title = "Introduction to Binomial Expansion",
    Slug = "introduction-to-binomial-expansion",
    Summary = "Learn the fundamentals of binomial expansion, understand the binomial theorem, and explore how powers of binomial expressions are expanded systematically.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Binomial Expansion"].Id,
    Title = "Applying the Binomial Theorem",
    Slug = "applying-the-binomial-theorem",
    Summary = "Explore Pascal's Triangle, binomial coefficients, and methods for finding general terms and solving expansion problems using the binomial theorem.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Binomial Expansion"].Id,
    Title = "Applications and Practice of Binomial Expansion",
    Slug = "applications-and-practice-of-binomial-expansion",
    Summary = "Apply binomial expansion concepts to solve advanced algebraic problems and explore applications in probability, calculus, computer science, and engineering.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},
// ==========================================================
// Mathematical Induction
// ==========================================================

new Lesson
{
    TopicId = topics["Mathematical Induction"].Id,
    Title = "Introduction to Mathematical Induction",
    Slug = "introduction-to-mathematical-induction",
    Summary = "Learn the fundamentals of mathematical induction, understand the base case and inductive step, and discover how induction is used to prove statements involving natural numbers.",
    Content = "",
    Difficulty = DifficultyLevel.Begineer,
    ReadingTimeMinutes = 10,
    IsPublished = true,
    DisplayOrder = 1,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Mathematical Induction"].Id,
    Title = "Proving Statements Using Mathematical Induction",
    Slug = "proving-statements-using-mathematical-induction",
    Summary = "Explore the process of mathematical induction by proving algebraic identities, divisibility properties, inequalities, and sequence formulas step-by-step.",
    Content = "",
    Difficulty = DifficultyLevel.Intermediate,
    ReadingTimeMinutes = 15,
    IsPublished = true,
    DisplayOrder = 2,
    ThumbnailUrl = ""
},

new Lesson
{
    TopicId = topics["Mathematical Induction"].Id,
    Title = "Applications and Practice of Mathematical Induction",
    Slug = "applications-and-practice-of-mathematical-induction",
    Summary = "Apply mathematical induction to solve advanced proof-based problems and explore its applications in mathematics, computer science, algorithms, and discrete structures.",
    Content = "",
    Difficulty = DifficultyLevel.Advance,
    ReadingTimeMinutes = 20,
    IsPublished = true,
    DisplayOrder = 3,
    ThumbnailUrl = ""
},

























        };

        await context.Lessons.AddRangeAsync(lessons);
        await context.SaveChangesAsync();
    }
}